### ISSUE TITLE
Merge Nested not showing up

### ISSUE THREAD

**Issue by hokutonanto** [georgeguimaraes/logseq-plugin-merge-nested-blocks-into-one#2]
Hi there,

First off, thanks for creating this plugin, it seems exactly what I needed!
I installed it in Logseq from the plugins page, but even after restarting it, I don't see the option in the right-click drop-down menu:
![image](https://user-images.githubusercontent.com/23059969/202334356-eaa6600f-1249-4d0d-8146-2f43d608c8b0.png)

Am I missing something?

I'm using the latest Logseq release, 0.8.11

**Comment by georgeguimaraes** [comment]
You are right.
v1.0.7 is not working properly.

I'll take a look.

**Comment by georgeguimaraes** [comment]
Thanks for pointing it out!

**Comment by georgeguimaraes** [comment]
Released a new version v1.0.9. Can you update and test it?

**Comment by hokutonanto** [comment]
Thanks @georgeguimaraes !
I've updated to v1.0.8 (I guess that's the one you meant), and it works great.
