### ISSUE TITLE
Options to change spacing between lines?

### ISSUE THREAD

**Issue by mruderman** [georgeguimaraes/logseq-plugin-merge-nested-blocks-into-one#3]
Great plugin, thank you! Is there a way to change the default behavior so that blocks are merged together without an empty line between the next line?

**Comment by georgeguimaraes** [comment]
Hi. Thank you. 

Right now it’s not possible. But since you’re asking, I’ll try to create a settings panel with that config. It’s gonna be a good way to learn how to do that. No promises though as I never did that before :)

**Comment by georgeguimaraes** [comment]
Wow, took me a long time, but i did it! :)

![CleanShot 2023-09-01 at 11 55 48](https://github.com/georgeguimaraes/logseq-plugin-merge-nested-blocks-into-one/assets/2929/91e9f42e-600a-45d8-a7f7-ccd7b908f810)

new version should come automatically
